#!/usr/bin/env bash
# Generates skill-index.yaml from individual skill-metadata.yaml files.
# Usage: generate-index.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS_DIR="$REPO_ROOT/skills"
INDEX_FILE="$REPO_ROOT/skill-index.yaml"

GENERATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Start building the index
cat > "$INDEX_FILE" <<EOF
# Auto-generated by scripts/generate-index.sh — do not edit manually
version: 1.0.0
generated: $GENERATED_AT
skills:
EOF

# Process each skill directory (sorted for deterministic output)
for meta in $(find "$SKILLS_DIR" -maxdepth 2 -name "skill-metadata.yaml" | sort); do
    skill_dir="$(dirname "$meta")"
    skill_name="$(basename "$skill_dir")"
    rel_path="skills/$skill_name"

    # Extract fields from metadata
    description=$(grep "^description:" "$meta" | head -1 | sed 's/^description:[[:space:]]*//')
    version=$(grep "^version:" "$meta" | head -1 | sed 's/^version:[[:space:]]*//')
    status=$(grep "^status:" "$meta" | head -1 | sed 's/^status:[[:space:]]*//')

    # Extract tags (single-line list format)
    tags=$(grep "^tags:" "$meta" | head -1 | sed 's/^tags:[[:space:]]*//')

    # Extract MCP server packages
    mcp_packages=""
    in_mcp=false
    while IFS= read -r line; do
        if [[ "$line" =~ ^mcp-servers: ]]; then
            # Skip inline empty list
            [[ "$line" =~ \[\] ]] && continue
            in_mcp=true
            continue
        fi
        if $in_mcp; then
            # Stop at next top-level key or empty line followed by key
            if [[ "$line" =~ ^[a-z] ]]; then
                in_mcp=false
                continue
            fi
            pkg=$(echo "$line" | grep "package:" | sed 's/.*package:[[:space:]]*//' || true)
            if [[ -n "$pkg" ]]; then
                [[ -n "$mcp_packages" ]] && mcp_packages="$mcp_packages, $pkg" || mcp_packages="$pkg"
            fi
        fi
    done < "$meta"

    # Extract system deps (name and min-version may be on separate lines within same item)
    system_deps=""
    in_sys=false
    cur_dep_name=""
    cur_dep_ver=""
    while IFS= read -r line; do
        if [[ "$line" =~ ^system-deps: ]]; then
            [[ "$line" =~ \[\] ]] && continue
            in_sys=true
            continue
        fi
        if $in_sys; then
            # New top-level key ends the section
            if [[ "$line" =~ ^[a-z] ]]; then
                # Flush last dep
                if [[ -n "$cur_dep_name" ]]; then
                    dep_str="$cur_dep_name"
                    [[ -n "$cur_dep_ver" ]] && dep_str="${cur_dep_name}>=${cur_dep_ver}"
                    [[ -n "$system_deps" ]] && system_deps="$system_deps, $dep_str" || system_deps="$dep_str"
                fi
                cur_dep_name="" ; cur_dep_ver=""
                in_sys=false
                continue
            fi
            # New list item starts with "  - "
            if [[ "$line" =~ ^[[:space:]]*-[[:space:]] ]]; then
                # Flush previous dep
                if [[ -n "$cur_dep_name" ]]; then
                    dep_str="$cur_dep_name"
                    [[ -n "$cur_dep_ver" ]] && dep_str="${cur_dep_name}>=${cur_dep_ver}"
                    [[ -n "$system_deps" ]] && system_deps="$system_deps, $dep_str" || system_deps="$dep_str"
                fi
                cur_dep_name="" ; cur_dep_ver=""
            fi
            n=$(echo "$line" | grep "name:" | sed 's/.*name:[[:space:]]*//' || true)
            [[ -n "$n" ]] && cur_dep_name="$n"
            v=$(echo "$line" | grep "min-version:" | sed 's/.*min-version:[[:space:]]*//' | tr -d '"' || true)
            [[ -n "$v" ]] && cur_dep_ver="$v"
        fi
    done < "$meta"
    # Flush last dep if file ends inside system-deps
    if $in_sys && [[ -n "$cur_dep_name" ]]; then
        dep_str="$cur_dep_name"
        [[ -n "$cur_dep_ver" ]] && dep_str="${cur_dep_name}>=${cur_dep_ver}"
        [[ -n "$system_deps" ]] && system_deps="$system_deps, $dep_str" || system_deps="$dep_str"
    fi

    # Write skill entry
    cat >> "$INDEX_FILE" <<EOF
  $skill_name:
    description: $description
    path: $rel_path
    version: $version
    tags: $tags
    status: $status
EOF

    # Add requires section if there are dependencies
    if [[ -n "$mcp_packages" ]] || [[ -n "$system_deps" ]]; then
        echo "    requires:" >> "$INDEX_FILE"
        [[ -n "$mcp_packages" ]] && echo "      mcp-servers: [$mcp_packages]" >> "$INDEX_FILE"
        [[ -n "$system_deps" ]] && echo "      system: [$system_deps]" >> "$INDEX_FILE"
    fi
done

echo "Generated $INDEX_FILE"
